[project]
name = "octask-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flet>=0.28.3",
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "flet[all]>=0.28.3",
]
